repository: 4richardchen/4richardchen.github.com
permalink: /:title
theme: jekyll-theme-cayman
plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
future: true
exclude:
  - README.md
  - Dockerfile
  - docker-compose.yml
  - Gemfile*
  - .git*